### ISSUE TITLE
Create images for other aws regions and update cloud formation

### ISSUE THREAD

**Issue by aws-rahul-chugh** [vgribok/modernization-unicorn-store#26]
Right now, cloud formation works only in us-east-1 and us-west-2 as ec2 image only exist in those two region. Create ec2 images in other regions as well.

Scope creep: :-) Please install [.NET SDK 3](https://dotnet.microsoft.com/download/dotnet-core/3.0) on the image as next version of the app will be .NET Core 3.0.

**Comment by vgribok** [comment]
An internal script is created replicating a collection of AMIs from one AWS region to a set of other AWS regions.
